name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app --max-line-length=120

      - name: Test Docker build
        run: |
          docker build -t mlops-gpt2-app ./app

      - name: (Optional) Push Docker image to registry
        if: false  # Set to true and configure for your registry
        run: echo "Add Docker push step here"
